### PR TITLE
Update to bytestring-0.10.8.2

### PR DESCRIPTION
**Pull request by RyanGlScott**
This was done by running `gen-sources.sh` after incrementing the version number.

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Friendly ping?

**Comment by RyanGlScott** [comment]
Ping?

**Comment by RyanGlScott** [comment]
Ping?

**Comment by RyanGlScott** [comment]
Ping?

**Comment by lpsmith** [comment]
My apologies.  I could add you to the maintainers list on Hackage, if you would like.

**Comment by RyanGlScott** [comment]
That would work for me!

**Comment by lpsmith** [comment]
Ok, I added `ryanglscott` to the maintainers list of bytestring-builder.

**Comment by RyanGlScott** [comment]
Thanks! That being said, I would still need the ability to merge this pull request in order to make this change happen.

**Pull request merged**
